all:
	gcc -o monster monster.c
	gcc -o world world.c logging.c

gameworld:
	gcc -o gameworld gameworld.c
monster:
	gcc -o monster monster.c

world:
	gcc -o world world.c logging.c

clean:
	rm -f *.o world monster
